[build]
  command = "yarn introspect && yarn codegen && yarn build"
  functions = "netlify/functions"
  publish = "out"
[[redirects]]
from = “/tips/*”
to = “/tips/[slug].html”
status = 200
force = true