[build]
  command = "yarn introspect && yarn codegen && yarn build"
  functions = "netlify/functions"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
  [plugins.inputs]
	build_dir_path = "frontend"
	custom_build_dir_name = ".next-build"